function getRandomImage() {
  //declare number of images and emotions
  var numFaces = 23;
  const emotions = ["sad", "happy", "scared", "angry", "surprised", "disgusted"];

  // generate a number and provide to the image to generate randomly  
  var faceNum = Math.floor(Math.random() * numFaces) + 1;
  var emoNum = Math.floor(Math.random() * emotions.length);

  //print the images generated by a random number  
  document.getElementById("face").innerHTML += '<img src="imgs/Unknown-' + faceNum + '.jpg" style="width:25%" />';
  document.getElementById("emotion").innerHTML += '<a href="' + emotions[emoNum] + '.html">' + emotions[emoNum] + '</a>';

}

getRandomImage();